// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxUD-FEfQp94Vb4TacEAE1GgOIl4mC3U',
    appId: '1:191411125170:web:03d713094dd3b69d1602ab',
    messagingSenderId: '191411125170',
    projectId: 'messages-app-8580e',
    authDomain: 'messages-app-8580e.firebaseapp.com',
    storageBucket: 'messages-app-8580e.appspot.com',
    measurementId: 'G-CF4JZH8DBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLIjIru0gE5ThGfrOVPoUEB2UXohEGwA',
    appId: '1:191411125170:android:7610b787a41613ea1602ab',
    messagingSenderId: '191411125170',
    projectId: 'messages-app-8580e',
    storageBucket: 'messages-app-8580e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQnYL8LOGDYtGkw3JytcUIwBiihUA2KQ',
    appId: '1:191411125170:ios:69112944626ea8f11602ab',
    messagingSenderId: '191411125170',
    projectId: 'messages-app-8580e',
    storageBucket: 'messages-app-8580e.appspot.com',
    iosBundleId: 'com.deignercastle.messagesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQnYL8LOGDYtGkw3JytcUIwBiihUA2KQ',
    appId: '1:191411125170:ios:52a32ff99ef479b31602ab',
    messagingSenderId: '191411125170',
    projectId: 'messages-app-8580e',
    storageBucket: 'messages-app-8580e.appspot.com',
    iosBundleId: 'com.deignercastle.messagesapp.RunnerTests',
  );
}
